spring.profiles.active: dev

server.port: 12345

spring:
  application:
    name: selective-process-zup-innovation
  datasource:
    driver-class-name: ${ENV_DRIVER_CLASS_NAME}
    url: ${ENV_DATASOURCE_URL}
    username: ${ENV_DATASOURCE_SERVICE_USERNAME}
    password: ${ENV_DATASOURCE_SERVICE_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc.lob.non_contextual_creation: true
        show_sql: true
        ddl-auto: create
        hbm2ddl:
          auto: create
---

spring.profiles: dev

ENV_DATASOURCE_URL: jdbc:postgresql://postgres/selectiveprocess
ENV_DATASOURCE_SERVICE_USERNAME: zup
ENV_DATASOURCE_SERVICE_PASSWORD: zup
ENV_DRIVER_CLASS_NAME: org.postgresql.Driver

