version: "3.7"
services:
  postgres:
    image: postgres:9.6
    environment:
      POSTGRES_USER: zup
      POSTGRES_PASSWORD: zup
      POSTGRES_DB: selectiveprocess
    ports:
    - 5432:5432
  selective-process-zup-innovation:
    build: ../
    ports:
      - "12345:12345"
    links:
      - postgres
    environment:
      SPRING_PROFILES_ACTIVE: dev
      JAVA_HEAP_SIZE_MB: 1024
